### ISSUE TITLE
3G or 3.5G

### ISSUE THREAD

**Issue by Dragsprit** [uavpal/disco4g#79]
Hello
I want to learn if it can be usable with 3g or 3.5g.
Thanks

**Comment by s0ftice** [comment]
US (CDMA2000): no, due to modem incompatibility.

Rest of world (W-CMDA/UMTS, HSPA): technically yes, but the bandwidth required can't be provided constantly and reliably most of the time. It works fine when disabling video (controls and telemetry only), which defeats the purpose of most pilot's use case.
